(1,82,'Fizyka','consequat purus. Maecenas',30,'Attendace'),
(2,55,'Fizyka','semper erat, in',30,'Attendace'),
(3,45,'Matematyka','aliquet lobortis, nisi',15,'Exam'),
(4,89,'Matematyka','montes, nascetur ridiculus',15,'Exam'),
(5,26,'Angielski','adipiscing non, luctus sit amet, faucibus ut,',45,'Internship'),
(6,68,'Angielski','gravida sagittis. Duis',45,'Internship'),
(7,60,'Chemia','aliquam arcu. Aliquam ultrices iaculis',10,'Attendace'),
(8,54,'Chemia','blandit. Nam nulla magna,',10,'Attendace'),
(9,84,'Biology','dignissim magna a tortor.',12.5,'Exam'),
(10,34,'Biology','ipsum. Curabitur consequat,',12.5,'Exam'),
(11,53,'Data Science','ultrices.',60,'Internship'),
(12,58,'Data Science','nibh. Quisque nonummy ipsum',60,'Internship'),
(13,66,'Informatyka','magna et ipsum cursus vestibulum. Mauris magna.',30,'Attendace'),
(14,14,'Informatyka','sed, est. Nunc laoreet lectus',30,'Attendace'),
(15,41,'Chiński','ullamcorper viverra. Maecenas iaculis aliquet diam.',15,'Exam'),
(16,18,'Chiński','malesuada fames ac turpis egestas.',15,'Exam'),
(17,96,'Programowanie Obiektowe','dignissim pharetra. Nam ac',45,'Internship'),
(18,26,'Programowanie Obiektowe','Nam interdum enim non',45,'Internship'),
(19,20,'Podstawy Baz Danych','lectus. Nullam suscipit, est',10,'Attendace'),
(20,92,'Podstawy Baz Danych','Aliquam gravida mauris ut',10,'Attendace'),
(21,42,'Kompetencje Interpersonalne','netus et',12.5,'Exam'),
(22,22,'Kompetencje Interpersonalne','Etiam gravida molestie arcu.',12.5,'Exam'),
(23,4,'Ochrona własności inteleuktualnej','tempus non, lacinia at, iaculis',60,'Internship'),
(24,17,'Ochrona własności inteleuktualnej','augue eu tellus. Phasellus elit',60,'Internship'),
(25,50,'Fizyka','arcu ac orci. Ut semper',30,'Attendace'),
(26,98,'Fizyka','Quisque varius. Nam porttitor scelerisque',30,'Attendace'),
(27,88,'Matematyka','massa. Integer vitae nibh.',15,'Exam'),
(28,51,'Matematyka','ultrices. Duis volutpat nunc',15,'Exam'),
(29,25,'Angielski','tincidunt congue turpis.',45,'Internship'),
(30,91,'Angielski','erat nonummy',45,'Internship'),
(31,59,'Chemia','eleifend, nunc risus',10,'Attendace'),
(32,57,'Chemia','libero. Donec consectetuer mauris id sapien. Cras',10,'Attendace'),
(33,86,'Biology','quis',12.5,'Exam'),
(34,87,'Biology','augue. Sed molestie. Sed',12.5,'Exam'),
(35,95,'Data Science','adipiscing elit. Etiam',60,'Internship'),
(36,47,'Data Science','odio a purus. Duis elementum, dui quis',60,'Internship'),
(37,58,'Informatyka','facilisis lorem tristique aliquet. Phasellus fermentum',30,'Attendace'),
(38,39,'Informatyka','at, egestas a, scelerisque sed, sapien. Nunc',30,'Attendace'),
(39,5,'Chiński','justo. Praesent',15,'Exam'),
(40,95,'Chiński','tincidunt. Donec',15,'Exam'),
(41,91,'Programowanie Obiektowe','a',45,'Internship'),
(42,7,'Programowanie Obiektowe','blandit. Nam nulla magna, malesuada vel, convallis',45,'Internship'),
(43,12,'Podstawy Baz Danych','bibendum. Donec felis orci, adipiscing non,',10,'Attendace'),
(44,46,'Podstawy Baz Danych','id, mollis nec, cursus',10,'Attendace'),
(45,57,'Kompetencje Interpersonalne','lacinia mattis. Integer eu lacus. Quisque',12.5,'Exam'),
(46,84,'Kompetencje Interpersonalne','nec tellus. Nunc',12.5,'Exam'),
(47,86,'Ochrona własności inteleuktualnej','Morbi quis urna.',60,'Internship'),
(48,63,'Ochrona własności inteleuktualnej','diam. Pellentesque habitant',60,'Internship'),
(49,19,'Fizyka','egestas blandit.',30,'Attendace'),
(50,61,'Fizyka','lacus, varius et, euismod et,',30,'Attendace');
