EXEC AddSubject 82, 'Fizyka', 'consequat purus. Maecenas', 30, 'Attendance'; 
EXEC AddSubject 55, 'Fizyka', 'semper erat, in', 30, 'Attendance'; 
EXEC AddSubject 45, 'Matematyka', 'aliquet lobortis, nisi', 15, 'Exam';
EXEC AddSubject 89, 'Matematyka', 'montes, nascetur ridiculus', 15, 'Exam';
EXEC AddSubject 26, 'Angielski', 'adipiscing non, luctus sit amet, faucibus ut,', 45, 'Internship';
EXEC AddSubject 68, 'Angielski', 'gravida sagittis. Duis', 45, 'Internship';
EXEC AddSubject 60, 'Chemia', 'aliquam arcu. Aliquam ultrices iaculis', 10, 'Attendance';
EXEC AddSubject 54, 'Chemia', 'blandit. Nam nulla magna,', 10, 'Attendance';
EXEC AddSubject 84, 'Biology', 'dignissim magna a tortor.', 12.5, 'Exam';
EXEC AddSubject 34, 'Biology', 'ipsum. Curabitur consequat,', 12.5, 'Exam';
EXEC AddSubject 53, 'Data Science', 'ultrices.', 60, 'Internship';
EXEC AddSubject 58, 'Data Science', 'nibh. Quisque nonummy ipsum', 60, 'Internship';
EXEC AddSubject 66, 'Informatyka', 'magna et ipsum cursus vestibulum. Mauris magna.', 30, 'Attendance';
EXEC AddSubject 14, 'Informatyka', 'sed, est. Nunc laoreet lectus', 30, 'Attendance';
EXEC AddSubject 41, 'Chiński', 'ullamcorper viverra. Maecenas iaculis aliquet diam.', 15, 'Exam';
EXEC AddSubject 18, 'Chiński', 'malesuada fames ac turpis egestas.', 15, 'Exam';
EXEC AddSubject 96, 'Programowanie Obiektowe', 'dignissim pharetra. Nam ac', 45, 'Internship';
EXEC AddSubject 26, 'Programowanie Obiektowe', 'Nam interdum enim non', 45, 'Internship';
EXEC AddSubject 20, 'Podstawy Baz Danych', 'lectus. Nullam suscipit, est', 10, 'Attendance';
EXEC AddSubject 92, 'Podstawy Baz Danych', 'Aliquam gravida mauris ut', 10, 'Attendance';
EXEC AddSubject 42, 'Kompetencje Interpersonalne', 'netus et', 12.5, 'Exam';
EXEC AddSubject 22, 'Kompetencje Interpersonalne', 'Etiam gravida molestie arcu.', 12.5, 'Exam';
EXEC AddSubject 4, 'Ochrona własności inteleuktualnej', 'tempus non, lacinia at, iaculis', 60, 'Internship';
EXEC AddSubject 17, 'Ochrona własności inteleuktualnej', 'augue eu tellus. Phasellus elit', 60, 'Internship';
EXEC AddSubject 50, 'Fizyka', 'arcu ac orci. Ut semper', 30, 'Attendance';
EXEC AddSubject 98, 'Fizyka', 'Quisque varius. Nam porttitor scelerisque', 30, 'Attendance';
EXEC AddSubject 88, 'Matematyka', 'massa. Integer vitae nibh.', 15, 'Exam';
EXEC AddSubject 51, 'Matematyka', 'ultrices. Duis volutpat nunc', 15, 'Exam';
EXEC AddSubject 25, 'Angielski', 'tincidunt congue turpis.', 45, 'Internship';
EXEC AddSubject 91, 'Angielski', 'erat nonummy', 45, 'Internship';
EXEC AddSubject 59, 'Chemia', 'eleifend, nunc risus', 10, 'Attendance';
EXEC AddSubject 57, 'Chemia', 'libero. Donec consectetuer mauris id sapien. Cras', 10, 'Attendance';
EXEC AddSubject 86, 'Biology', 'quis', 12.5, 'Exam';
EXEC AddSubject 87, 'Biology', 'augue. Sed molestie. Sed', 12.5, 'Exam';
EXEC AddSubject 95, 'Data Science', 'adipiscing elit. Etiam', 60, 'Internship';
EXEC AddSubject 47, 'Data Science', 'odio a purus. Duis elementum, dui quis', 60, 'Internship';
EXEC AddSubject 58, 'Informatyka', 'facilisis lorem tristique aliquet. Phasellus fermentum', 30, 'Attendance';
EXEC AddSubject 39, 'Informatyka', 'at, egestas a, scelerisque sed, sapien. Nunc', 30, 'Attendance';
EXEC AddSubject 5, 'Chiński', 'justo. Praesent', 15, 'Exam';
EXEC AddSubject 95, 'Chiński', 'tincidunt. Donec', 15, 'Exam';
EXEC AddSubject 91, 'Programowanie Obiektowe', 'a', 45, 'Internship';
EXEC AddSubject 7, 'Programowanie Obiektowe', 'blandit. Nam nulla magna, malesuada vel, convallis', 45, 'Internship';
EXEC AddSubject 12, 'Podstawy Baz Danych', 'bibendum. Donec felis orci, adipiscing non,', 10, 'Attendance';
EXEC AddSubject 46, 'Podstawy Baz Danych', 'id, mollis nec, cursus', 10, 'Attendance';
EXEC AddSubject 57, 'Kompetencje Interpersonalne', 'lacinia mattis. Integer eu lacus. Quisque', 12.5, 'Exam';
EXEC AddSubject 84, 'Kompetencje Interpersonalne', 'nec tellus. Nunc', 12.5, 'Exam';
EXEC AddSubject 86, 'Ochrona własności inteleuktualnej', 'Morbi quis urna.', 60, 'Internship';
EXEC AddSubject 63, 'Ochrona własności inteleuktualnej', 'diam. Pellentesque habitant', 60, 'Internship';
EXEC AddSubject 19, 'Fizyka', 'egestas blandit.', 30, 'Attendance';
EXEC AddSubject 61, 'Fizyka', 'lacus, varius et, euismod et,', 30, 'Attendance';